name: main

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3.2.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-core-${{ hashFiles('**/build.gradle.kts', '**/build.gradle', '**/libs.versions.toml') }}
          restore-keys: |
            gradle-deps

      - name: Cache Gradle Build
        uses: actions/cache@v3.2.4
        with:
          path: |
            ~/.gradle/caches/build-cache-*
            ~/.gradle/buildOutputCleanup/cache.properties
          key: gradle-builds-core-${{ github.sha }}
          restore-keys: |
            gradle-builds

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          echo "MIIKaQIBAzCCCiIGCSqGSIb3DQEHAaCCChMEggoPMIIKCzCCBbIGCSqGSIb3DQEHAaCCBaMEggWfMIIFmzCCBZcGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFPzffAAvkC9WtT2AFyEtj1qC7gIDAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQfhNQWGVfuNOXdTET8z8CAwSCBND0RpXUhWqUm/QOPlLk3vB61gxLAFj9QyqH98oDrW5wL3DTYUzHOhhV1UqIbeKiGk5LMmjTDZ/XeTui37fSferKFSHLHsJfTGi4yf7FLo9qjA/ek1Hps95Q1RfJ1IlvFia0IGZlPT1d7aUgVMuc1fDSTKBBwIny9/3duV7srTyxginqt+TNvPUB/3B6CNGVtktnqS1B/418zzKSsB5FG+ty3JNgOO+7MN68ExDB5vzpppLsGzS27rXz5vUkyLCTM97YINuhooucJnjkJiqEZmALcCS++lUHrWspKc/660XeiMrLDUZknmqsV8qIqyv0D7Lt66yCuuZQ1XTcUQiKsZGNgBjRD7PCRvbfbFOyjygLhIReVS+dBAC/l9qPlacJcWDcUV9UYwOowXhJoMstPtCm5s9DP1BZXf8OXsyP2xhITS9rIP4zk0U4O8luCwQ+amE2QKrxTp14ymAERmehQvW81F95WFpu0Mdmu+O+CQXohqy/tRBjiHnnuBRQoOxFRCZ3KDfrqxZbxzMELsD+VGk74XBXVoq3dsZelQtChTs+n4STsB97MpmM2qENjvNKHs7QUYc2efzRq99DluHcwxZa61IDZGSGYpQE0R2XI7J6lYpQaVtaF2erpXfY89kUP8upzboZ4u1DyQZCigs86f/4ThvUdJnO1A8pSmbEdsHTmFVmOaI0eRUN0uo5TqBvCMBK6gwP6asrJjUNSNfL5lQ0+9PlgxsPQQK4me0qK7ogVJBK5dorPzi0DZnCcG7ZGbkgst0ZT9+8TJnEFSwl1bgK+4TAGE/oZgkx9PrAje9zQgIyylAbIusnlzu0m0bykD9yujb7G090Olge/F5FvQJwP96k2t+257Kib8+Iwwy3vwg228Gf9Y/c6Gkr8cE59FrnzW4KLTDgtVks70yV/NZyTU/3Iur1EWStjn6Yg/2msX/T5FHP9m3QsFQjtDw5ZxjCwUD7/6LwyxAU3qQW+gau5ENqoFyJPL1Rf6pfar2uWIUfmBko70Q0Yhuk2kRT9sRyJfqpXviweMF+40EGJhMDSbKfKM36BcLWEXYHCHTInIQ2aqg93PYTBxMk4hxN4UQcKnBju6bbcNo5WJGMEg5MPhsRhRYfHETvEaYBUu3Rp5wPcCXVKiIxjMMNXfTES89v9gVKlyRQe+DTlKV5MrCTSD8KNdxoIERIqpfRgHr3DAdYYYGF+E417Qrfjot0TY7PYYhuQX/wJbi5TKtpvlKsxh0FQfh8idHzPLJAENyQ9w0/BS0prXqRQgHeVDT2C+sPYTBzR0BDKXZPZi1ddV2pguceAm/rDQnhCkFg1HnRyk4lt0/0bxxxhlfhefUMX5edIqqMMEpW2NdHTlJXbqFy/iwpflf0itKFPSoROJFNm5yPiDvSmhYE5F2iK2lqQYTtbIBlrJdRKPyzaZ9Mw3ohOsETFOB9ThYT24vyj68hYR8Q0ya8chjeoOmp7tt6SJD2aV45+piAEZbFRppKyWF9diSqAJk9WJag1IHBerXTiZ539bFXeLvy5jkOcdSsHBVsejvI8KvmtdYEmC69F5Y8gU4dB8q7737KkCL7Kf2x6DW+TEghbvt7jyIJOtpEDXLKCjrFVnmhP17q4azuO8eL47GEKHPo6a7cPaDUXY9JYzFEMB8GCSqGSIb3DQEJFDESHhAAMQAyADMANAA1ADYANwA4MCEGCSqGSIb3DQEJFTEUBBJUaW1lIDE3MDQyNjY2MzU5NzEwggRRBgkqhkiG9w0BBwagggRCMIIEPgIBADCCBDcGCSqGSIb3DQEHATBmBgkqhkiG9w0BBQ0wWTA4BgkqhkiG9w0BBQwwKwQUF5U1I8bCfqHQL6Txa0RTpUT/iqcCAicQAgEgMAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBDxPKWQ2EL0suQixbyzw+jfgIIDwE6yBs+g8aCHgFRbWQwcqXQNj/KS9Ez1n2ab7SwUBFIfm61eip1QMMfv0YWQRAUimCo+gfLg35yfFHVQmYwKenVdIIz5VS+0V7UNFGnyCWUMBYDe1p8DKiX09f+dTXOFxXH4pJfUcViNN3l3++1f5DIXbUPqiPqdfQCXALmTmEPQ6xee8Pyqh0kGrc3lJmoDqjARwttMy6mRMil+iFWknVtq97bQByDVvBNP4KsAaQzQYyKu/tePNJdxHDkZT1tZ10pepFumNQfsUCW1z9gPr+fcKayVyfhKr7NFwmUqBtoN3EjrIUZG3VR5WMHUI9SASPy1paXAvXJpGtgIOZoDFVLCmLwSJDpaxvNuhp/NyLikYDyeUFxAlPymsmqkMwMAJWx8uWatf/jhLgxGJyCTITYBSalGSKIK2Cbk9kaRGrokk4ZEq4JVWNIxJINYxFCVy75gzM0Jk2m9W5USuX9YlbKN0ik4clEoZKiMFZIqMQloSMKDLADykNRsOa5HPd0N2mSF5P37ktNiWkri4hkbD85ItsVHbFylucwGEUr6y/Bl2/IMX7A5LxO5USPwQ7LEgErQF4OEXsvtPuf6bPUhZNWb5wsz7CmHYdIYwoQPTc8y7ijXNbgUuBT0pjMYMFMirOhXut55Qwv+YsNlzN8BP8Fj0RXJj5zLO5mAa0Fh8jPXut695v0ErsaFjtyHr/vWvxz2WDDAt/2R9nF49+yg4HTfoLmoi5j76sv+64JtGJqEAHsnZV2qYg3RNIkL7PVEMrHgafJHaYjW1xNbYkN+tsSWzPLH1pkt/M0HyYaYgKn24q+YR9Bg4zPr1lvBj/nN2Esed/s9ldBlabsbb31WMnpHLCe54B9Xk4VTU9WKeUfg4zXw9cZ7AVhzMQCr7FU/OIPKfaqI5beeDXbHCBjrVO9+u5loi+QRyfUoijyOFrIzwqbjfIowdJZvgQzUSc3nJ80WKYVuRP2t2+r5CsZDhgyYTNwWg5IBDRydxNNklvxfoHr3kCTmJU3LbJb3cqWrfZDrYQISkbIDYK3dSBmKop7fH8y+MAu+EFbXw0Jax6MjtVhTRfEmNIuNAgpnR2sYcXA5TtKf2B2N/l4+aEhdI6LZ0mBTKknaWSqosj36c1NHbAplCWzAlvpc0bS4kT2CWq0HGRGLcgVfMD7mUNawFIImLyzTwDCgdLGjRUc7EG5NjYs/Q9z7LNKmu1WGrrpykmSTpU5qX2sL5Tzrnou4YcG0MD0HJiAfshvxrhJPihhUvLTuAtqFZFtY4hSKNmuThDA+MCEwCQYFKw4DAhoFAAQU7JjJ8pdoPAWp0vJjAMP1kOr5QyYEFM9qJnUrPXN+pbDAMbW0o6xJ5kZ+AgMBhqA=" | base64 -d > keystore.jks
          cp -f keystore.jks ./app/c001apk.jks
          ls -hl
          ls -l ./app
          ./gradlew :app:assembleRelease --debug
        env:
          KEYSTORE_PATH: "../keystore.jks"
          KEYSTORE_PASSWORD: 12345678
          KEY_ALIAS: 12345678
          KEY_PASSWORD: 12345678

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        # don't upload the artifacts if it's a pull request
        if: ${{ !github.event.pull_request }}
        with:
          path: './app/build/outputs/*'
          name: build_output_${{ github.event.head_commit.id }}.zip
